### ISSUE TITLE
Allow switching event processor to be configurable; don't force use of subscribing event processor

### ISSUE THREAD

**Issue by sluehr** [everest-engineering/lhotse#18]
**Is your feature request related to a problem? Please describe.**
The design of the switching event processor mandates that every application use subscribing event processing unless performing replays.

**Describe the solution you'd like**
It should be configurable so that tracking event processors can be used out of the box if users so chose.

**Describe alternatives you've considered**

**Additional context**
The switching event processor was implemented to make it simple to reason about the order in which requests are processed but to also take advantage of TEPs during replays.

**Comment by ywangd** [comment]
Without using subscribing event processor, switch event processor by itself is not necessary. In this case, the configuration can just fallback to use stock tracking event processor. We can make this configurable, i.e. selected between TEP or Switching. 

The replay endpoint will need some adjustment, should be straightforward.
