### ISSUE TITLE
Introduce Sagas to the sample app.

### ISSUE THREAD

**Issue by sluehr** [everest-engineering/lhotse#26]
~~(And consider removing validation based on projections)~~

**Comment by ywangd** [comment]
I am still not clear how Saga could help removing "validation with projections". For an example, [organization needs to be enabled for an user to be created for it](https://github.com/everest-engineering/lhotse/blob/master/command-validation-support/src/main/java/engineering/everest/lhotse/axon/command/validators/OrganizationStatusValidator.java). How could this be fit into a Saga? Unless we break it into several steps like:
1. UserAggreggate creates user (but disabled) and publishs event
2. Saga receives the event and issues a command (register this user) to OrgAggregate 
3. OrgAggregate verifies its own status and publish an event accordingly
4. Saga recieves the event and issues a command to UserAggregate to either enable to delete the user
5. UserAggregate receives the command and publishes an event to say either "user is enabled" or "deleted"
6. Saga recieves the event and can stop this saga instance accordingly.

I think this could work. It is proliferation of commands and events. But maybe that is the right way to do DDD and event sourcing. Or do you have something different in mind?

**Comment by sluehr** [comment]
I think that the command could be routed to the OrganizationAggregate which would reject it. 

A reason for routing it to the organisation might be that we do not want to create a user until all the following preconditions are met:
 * organisation is enabled
 * email address is unique
 * user has confirmed the email address

If the organisation were enabled, then the OrganizationAggregate could emit an event to indicate that  NewUserRegistrationFlowStartedEvent was triggered.

A saga could then check if the email address was unique and whether the organisation was enabled _using projections_. These projections could be accessed via a DB query or via an API call to a user service (something that you'd want to extract down to the road anyway). The difference here is that a saga can deal with downtime in an extracted user service by periodically retrying until the user service becomes available again. Also, it is not a command that is being validated by an automated step in a workflow.

The next step might be the saga emitting a NewUserEmailConfirmationSentEvent which would trigger sending an email so a user can confirm their address. The user following that link is likely to dispatch a command to indicate that the email address was confirmed, emitting a UserEmailAddressConfirmedEvent which the saga could use to dispatch a command CompleteNewUserRegistrationCommand. This command would be routed to the UserAggregate repository to create a new user.

A lot more commands and events but the processing of the workflow has been moved into a saga and the events now capture the actual workflow. It is a far richer domain model with all processing decisions explicitly captured.

There are holes in the scenario above. For example, do we want a command dispatched everytime an email confirmation link is clicked or do we want to just emit multiple events? The events would be idempotent and the link would stop working after a while.....
