### ISSUE TITLE
Improve requesting user context pattern

### ISSUE THREAD

**Issue by sluehr** [everest-engineering/lhotse#53]
We should research whether it is possible to drop requestingUser from the explicit argument list because: (1) the API signature looks clunky with it; (2) we don't consistently have this extra userId in all methods; (3) the requestingUser should be kept implicitly throughout the context and injected when it is actually needed without the API consuming code to be aware of it.

_Originally posted by @ywangd in https://github.com/everest-engineering/lhotse/pull/48#discussion_r748785109_

**Comment by prasanna214** [comment]
Closing this issue as this approach has conflicts with role annotations that we are using on controller methods
cc: @sluehr
