### ISSUE TITLE
Document Keycloak CLI workings

### ISSUE THREAD

**Issue by ali-everest** [everest-engineering/lhotse#55]
There is some configuration required for the Keycloak CLI. 
We should introduce a README.md in the keycloak directory with some examples of how to manage Keycloak using the CLI. 

_Originally posted by @sluehr in https://github.com/everest-engineering/lhotse/pull/48#discussion_r741574078_

**Comment by sluehr** [comment]
TODO: can we use the CLI to generate the default-client secret key?

**Comment by sluehr** [comment]
Client secret is not required anymore for the very public web UI
