### ISSUE TITLE
Not use Hazelcast？

### ISSUE THREAD

**Issue by blling** [everest-engineering/lhotse#60]
**Describe the bug**
Not use Hazelcast，but the `About` contains `Hazelcast`.

**To Reproduce**
1. See github `About` of this project
![图片](https://user-images.githubusercontent.com/26540808/160755060-18c074c2-00a4-4e39-b67b-6dd890316920.png)

**Expected behavior**
Remove `Hazelcast`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sluehr** [comment]
Thanks for the heads up! Hazelcast was recently removed. I've updated the about blurb.
