### ISSUE TITLE
Update to Spring Boot 3.0

### ISSUE THREAD

**Issue by sluehr** [everest-engineering/lhotse#62]
This will require all supporting libraries to be updated. 

We need to wait for Axon:
https://github.com/AxonFramework/AxonFramework/issues/2430

There is also work to be done with the Keycloak integration as the Keycloak adapters are no longer supported:
https://www.keycloak.org/2022/02/adapter-deprecation

**Comment by arunzone** [comment]
Awaiting for Spring Boot 3.0 support 👍
