### ISSUE TITLE
Disable login via query parameters

### ISSUE THREAD

**Issue by sluehr** [everest-engineering/lhotse#9]
Accepting credentials as query parameters leads them to be captured in logs which may not be as well guarded or may be exported to third-party analysis tools.

**Comment by ywangd** [comment]
I am not sure if this is necessary. The system does **not** automatically log request parameters. In addition, there are scenarios where HTTP header is not an option, e.g. websocket.

**Comment by sluehr** [comment]
It's a concern for projects that need to undergo security compliance. The application may not be logging by default but load balancers performing TLS termination would be.

We should make it configurable (and disabled by default)

**Comment by sluehr** [comment]
I'm inclined to close this issue as:
- we don't log by default
- we're likely to be using an off the shelf authentication/authorisation server next year
- projects that require this level of compliance are likely to have their own authentication system in use

**Comment by ywangd** [comment]
I agree. Authentication is likely controlled elsewhere with SSO. Spring's new change of not providing an auth server is a hint that regular applications should not concern itself other than being a relying party/service provider in the SSO scheme.
